<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSignaledComments()
    {
        return $this->createQueryBuilder('c')
            ->where('c.signaled = true')
            ->getQuery()
            ->getResult();
    }
}
