security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:     ROLE_AUTHOR

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: alaska, roles: [ROLE_ADMIN] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /author/
            logout:
                path: logout
                target: /



    access_control:
        - { path: ^/author, roles: ROLE_AUTHOR }

