parameters:
    #parameter_name: value

services:
    article_manager:
        class: AppBundle\Services\ArticleManager
        arguments:
            - "@doctrine.orm.entity_manager"

    comments_manager:
            class: AppBundle\Services\CommentsManager
            arguments:
                - "@doctrine.orm.entity_manager"

    mail:
            class: AppBundle\Services\MailService
            arguments:
                - "@mailer"
                - "@twig"

    app.twig_extension:
            class: AppBundle\Twig\FilterExtension
            public: false
            tags:
                - { name: twig.extension }