# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    article_management_in_bdd:
        class: AppBundle\Services\ArticleManagementInBdd
        arguments:
            - "@doctrine.orm.entity_manager"
    comments_management:
            class: AppBundle\Services\CommentsManagement
            arguments:
                - "@doctrine.orm.entity_manager"
    number_of_articles:
        class: AppBundle\Services\NumberOfArticles