# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    gestion_article_dans_bdd:
        class: AppBundle\Services\GestionArticleDansBdd
        arguments:
            - "@doctrine.orm.entity_manager"
    compte_nombre_articles:
        class: AppBundle\Services\CompteNombreArticles