# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    bdd_recording:
        class: AppBundle\Services\BddRecording
        arguments:
            - "@doctrine.orm.entity_manager"
