parameters:
    #parameter_name: value

services:
    article_management_in_bdd:
        class: AppBundle\Services\ArticleManagementInBdd
        arguments:
            - "@doctrine.orm.entity_manager"

    comments_management:
            class: AppBundle\Services\CommentsManagement
            arguments:
                - "@doctrine.orm.entity_manager"

    number_of_something:
        class: AppBundle\Services\NumberOfSomething

    mail:
            class: AppBundle\Services\MailService
            arguments:
                - "@mailer"
                - "@twig"
